### ISSUE TITLE
Please consider renaming the org

### ISSUE THREAD

**Issue by flga** [go-standard/project-layout#7]
This repo presently explicitly contradicts `doc/modules/layout` regarding `internal`.

I acknowledge that the link to `doc/modules/layout` is salient, my main concern is the fact that this repo explicitly contradicts it ***while*** being under a problematic org name.

If the goal is for this repo to be a vehicle for opinion, then it should be placed under a different org.
If the goal is to serve as a counterweight to `golang-standards`, we already have `doc/modules/layout` so it's hard to pinpoint (at least for me) how valuable would it be to just have another echo.

I am posting this because I've noticed it getting shared with newcomers looking for guidance. Having contradicting opinions is fine, having them under `go-standard` re-opens the same discussions had around `golang-standards`.

**Comment by ldemailly** [comment]
it doesn’t contradict the go doc, it just points out that for most people and most code bases internal is counter productive (and again the official doc just mentions that internal _may_ be useful)

**Comment by flga** [comment]
> it doesn’t contradict the go doc, it just points out that for most people and most code bases internal is counter productive (and again the official doc just mentions that internal _may_ be useful)

`/doc/modules/layout` unequivocally advocates for the use of `internal` for "supporting packages".

> Larger packages or commands may benefit from splitting off some functionality into supporting packages. Initially, it’s recommended placing such packages into a directory named internal

> It’s recommended to keep packages in internal as much as possible.

**Comment by jrwren** [comment]
The README seems clear to me.

**Comment by ldemailly** [comment]
Here is btw the version that clearly show "opinion" https://laurentsv.com/blog/2024/10/19/no-nonsense-go-package-layout.html if anyone is interested to give feedback (I did steal some language from here)
